config/routes.rb
Rails.application.routes.draw do


    ActiveAdmin.routes(self)


    delete 'comments/:id' => 'comments#destroy', format: 'js'


    get 'comments/new'
    #  get 'notifications/create'

    #  get 'notifications/destroy'

    get 'users/show'

    get 'user/show'

    get 'likes/create'

    get 'likes/destroy'

    get '/users/modals/show' => 'comments_modals#show', as: 'show_comment_modal', format: 'js'

    devise_for :users, controllers: { registrations:'registrations', omniauth_callbacks: 'omniauth_callbacks' }

    get 'static_pages/home'
    get 'searches' => 'searches#show'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "static_pages#home"

    mount ActionCable.server => '/cable'

    resources :posts, only: [:create,:destroy]
    resources :likes, only: [:create,:destroy]
    resources :notifications, only: [:create,:destroy]
    resources :users, only: [:show]
    resources :friendships, only: [:create,:destroy]
    resources :comments, only:[:create,:destroy]
    resources :searches, only:[:show]
    resources :chat_rooms, only: [:new, :create, :show, :index]
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :notifications
    has_many :friendships, class_name: "Friendship"
    has_many :friends, through: :friendships
    has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
    has_many :inverse_friends, :through => :inverse_friendships, :source => :user
    has_one :block_status, class_name: "Block"
    has_attached_file :avatar, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "/user_fb_:style.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    scope :public_profile, -> { where public_profile: true }

    def self.search(search)
        where("name LIKE (:search)", search: "%#{search}%")
    end

    def self.from_omniauth(access_token)
        data = access_token.info
        user = User.where(email: data['email']).first

        unless user
            user = User.create(name: data['name'],
                               email: data['email'],
                               password: Devise.friendly_token[0,20]
                              )
        end
        user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include UsersHelper
    before_action :authenticate_user!
    def show
        @comment = current_user.comments.build
        @user = User.find(params[:id]).decorate
        @feed_items = @user.timeline
        set_title
    end

end

app/helpers/users_helper.rb
module UsersHelper
    def set_title
        user_friends = current_user.friends.to_a << current_user.inverse_friends.to_a
        user_friends_ids = user_friends.flatten.map(&:id)
        if @user.find_friend_request(current_user.id) || current_user.decorate.find_friend_request(params[:id])
            @title = "Friend request sent"

        elsif user_friends_ids.include?(params[:id].to_i)
            @title = "You are friends"

        else
            @title = "Add as a friend"
        end
    end
end

app/views/users/_user.html.erb
<br>
<%= image_tag @user.avatar.url(:medium),class: "profile-img" %>
<br>
<%= @user.name %>
<p><a href = "#modal1" class = "modal-trigger"> Friends(<%= @user.friends.count + @user.inverse_friends.count %>)</a></p>
<% if current_user != page_user %>
    <% if @title == "Add as a friend"  %>
        <p><%= link_to "#{@title}", notifications_path(:source => current_user, :dest => User.find(params[:id])), :method => :post %> </p>
    <% else %>
        <p> <%= @title %>  </p>
    <% end %>
<% else %>
    <p> <%= link_to "Edit profile", edit_user_registration_path %> </p>
<% end %>

app/views/users/show.html.erb
<div class = "row">
<div class = "container">


    <div class = "col s12 m4 l3 pull-l2">
        <%= render @user %>
    </div>

    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>Friends</h4>
            <% @user.all_friends.each do |f| %>
                <p><%= link_to f.name,f %> </p>
            <% end%>
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
        </div>
    </div>

    <% if can? :read, @user %>
    <div class = "col s12 m8 l9">
        <h4 class="center"> Timeline </h4>
        <%= render 'shared/feed' %>
    </div>
    <% end %>
</div>
</div>