config/routes.rb
Rails.application.routes.draw do


    ActiveAdmin.routes(self)


    delete 'comments/:id' => 'comments#destroy', format: 'js'


    get 'comments/new'
    #  get 'notifications/create'

    #  get 'notifications/destroy'

    get 'users/show'

    get 'user/show'

    get 'likes/create'

    get 'likes/destroy'

    get '/users/modals/show' => 'comments_modals#show', as: 'show_comment_modal', format: 'js'

    devise_for :users, controllers: { registrations:'registrations', omniauth_callbacks: 'omniauth_callbacks' }

    get 'static_pages/home'
    get 'searches' => 'searches#show'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "static_pages#home"

    mount ActionCable.server => '/cable'

    resources :posts, only: [:create,:destroy]
    resources :likes, only: [:create,:destroy]
    resources :notifications, only: [:create,:destroy]
    resources :users, only: [:show]
    resources :friendships, only: [:create,:destroy]
    resources :comments, only:[:create,:destroy]
    resources :searches, only:[:show]
    resources :chat_rooms, only: [:new, :create, :show, :index]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, length: {maximum:1000}, presence: true
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :correct_user,   only: :destroy
    def create
        @post = current_user.posts.build(post_params)
        authorize! :create,@post
        if @post.save
            flash[:success] = "Post created!"
            redirect_to root_url
        else
            @feed_items = []
            flash[:error] = "Your post can't be empty!"
            render 'static_pages/home'
        end
    end

    def destroy
        @post.destroy
        flash[:success] = "Post deleted"
        redirect_to request.referrer || root_url
    end
    def post_params
        params.require(:post).permit(:content, :picture)
    end
    def correct_user
        @post = current_user.posts.find_by(id: params[:id])
        redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="row post white">
<li  id="post- <%= post.id %>">
    <div class="col s12">
        <div class = "user">
            <%= image_tag post.user.avatar.url(:thumb), class:"avatar" %>
            <div class = "comment-title">
                <%= link_to post.user.name, post.user%>
            </div>
        </div>
    </div>
        <div class="col s12">
            <div class = "content left fr-view">
                <%= raw post.content %>
            </div>
        </div>
        <span class= "divider"></span>
        <% if like = liked_by_user(current_user,post) %>
            <div class="likes col s12">
                <%= link_to "Unlike", like_path(like.id),  :method => :delete %>
            </div>
        <% else %>
            <div class="likes col s12">
                <%= link_to fa_icon("thumbs-up",text:"Like"), likes_path(:post_id => post),  :method => :post %>
            </div>
        <% end %>
        <div class="col s6">
            <%=   pluralize(post.likes_count,"person") %> have liked this </div>
        <div class="timestamp col s6">
            Posted
            <%= time_ago_in_words(post.created_at) %> ago.
            <% if post.user == current_user %>
                <%= link_to "delete", post, method: :delete,
                    data: { confirm: "You sure?" } %>
            <% end %>
        </div>
        <div class = "col s12"> <%= link_to "Comments", show_comment_modal_path(post_id: post.id), remote: true %> </div>
</li>


<div id="modal" class="modal">
</div>

</div>

app/views/posts/_show_modal.html.erb
<div class="modal-content">

<% if can? :create, @comment %>
<h4>Comments</h4>
<%= form_for @comment, html: { class:"input-field", remote: true} do |f| %>
    <%= f.text_area :content, placeholder: "Say something..." %>
    <%= f.hidden_field :post_id, :value => @post.id %>
    <%= f.submit :create %>
<% end %>
<div class = "row">
    <%= render partial: 'shared/comments_feed', locals: {post:@post}  %>
</div>
</div>
<div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>

</div>
<% else %>
    <p> Blocked from commenting </p>

<% end %>